### ISSUE TITLE
Read/Write to sub-collection

### ISSUE THREAD

**Issue by Noller-BASCO** [Sichangi/node-red-contrib-cloud-firestore#1]
The documentation states that you can supply a string to access sub-collections "[string] collection or subCollection reference to write to". 

Firestore API requires: collection('A').doc('1').collection('B').doc('2') and does not support "A/1/B/2" path referance.

**Comment by Sichangi** [comment]
Hey @Noller-BASCO  ✋ 

You can reference a subCollection path as follows, it has to be an odd numberd path
```
collection('A/1/B').doc('2')
```
I have not added support for chaining the collection and document reference though

**Comment by Noller-BASCO** [comment]
@Sichangi  What would the syntax look like using the 'A/1/B' approach?
msg.firestore = {
        collection: 'A/1/B',
        document: '2',
        operation: 'add'
      }
Creates a top level collection with the name "A/1/B"

**Comment by Sichangi** [comment]
Yes that looks alright, have you tried it?

**Comment by Sichangi** [comment]
Oops sorry, you're right, It actually creates a top level name

**Comment by Noller-BASCO** [comment]
You beat me to it: 
![image](https://user-images.githubusercontent.com/37918959/50261733-88d2a600-03d3-11e9-97f8-57d97729f310.png)

![image](https://user-images.githubusercontent.com/37918959/50261698-57f27100-03d3-11e9-805f-5a53a71f2fbf.png)

Do you have plans to continue to develop the flow? Do you think getting sub-collection support will be a big deal? Any idea when you think you might be able to add support? I would love to help, but my node/javascript programming skills are very weak.

**Comment by Sichangi** [comment]
Hmm...  I have tried it on my instance once more and it seems to work just fine
![image](https://user-images.githubusercontent.com/16804232/50262436-6b78f880-0422-11e9-958d-ee4f85cb84fa.png)
![image](https://user-images.githubusercontent.com/16804232/50262480-9fecb480-0422-11e9-925c-2a528ac4f727.png)

**Comment by Noller-BASCO** [comment]
You are correct. minor syntax issue on my end:
I was missing the leading "/"
![image](https://user-images.githubusercontent.com/37918959/50262673-13b59f80-03d8-11e9-8152-ca5f6ac60369.png)

Thank you very much!

**Comment by Sichangi** [comment]
Even with your case, without the leading slash should work just fine

![image](https://user-images.githubusercontent.com/16804232/50262744-cfe88780-0423-11e9-82ba-00986ccb156d.png)

![image](https://user-images.githubusercontent.com/16804232/50262760-e5f64800-0423-11e9-91a8-1834b8452529.png)

**Comment by Sichangi** [comment]
And just a point to note, if you need to set a custom document name, use the ``set`` operation instead of the ``add`` operation
