### ISSUE TITLE
Using collection groups queries

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#10]
Hi,

It seams like there is no way to handle collection groups queries as [described here](https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query).

I'm willing to implement that but I'd like some insight if you already though about it. For example, should it be in a different node dedicated to it? Or should it be an option in the Write node?

Any hint will be appreciated :smile:

**Comment by sichangi** [comment]
Hello,
That's interesting, didn't notice that was actually there in the docs 😅,
Thanks for the heads up & PR, lemme review this
