### ISSUE TITLE
Multiple service accounts not working

### ISSUE THREAD

**Issue by deutzia8152** [sichangi/node-red-contrib-cloud-firestore#12]
Hi,

in firebaseAdminNode.js
``` js
if (!firebaseAdmin.apps.length) {
  firebaseAdmin.initializeApp({
    credential: firebaseAdmin.credential.cert(config.serviceAccountJson),
    databaseURL: `https://${config.serviceAccountJson.project_id}.firebaseio.com`,
    projectId: config.serviceAccountJson.project_id,
  })
  this.core = firebaseAdmin;
  this.firestore = firebaseAdmin.firestore();
} else {
  firebaseAdmin.app()
}
```
The first service account works fine.
Two or more service accounts do not work.no core and firestore.

I think it will be fixed below.
``` js
const subApp = firebaseAdmin.initializeApp({
  credential: firebaseAdmin.credential.cert(config.serviceAccountJson),
  databaseURL: `https://${config.serviceAccountJson.project_id}.firebaseio.com`,
  projectId: config.serviceAccountJson.project_id,
}, config.serviceAccountJson.project_id)
this.core = subApp;
this.firestore = subApp.firestore();
```

**Comment by sichangi** [comment]
Hi @deutzia8152 , 
Thanks for filing this issue,

Simply defining an additional application may not solve the overall problem,

Allowing users to define multiple applications either through the configuration node or dynamically through input may be a viable solution.

This might also solve [this issue](https://github.com/sichangi/node-red-contrib-cloud-firestore/issues/8)

**Comment by sichangi** [comment]
As proposed, this has been patched by this [commit](https://github.com/sichangi/node-red-contrib-cloud-firestore/commit/4e83ba0edfbdb40fd4cc1534e68ace7fc50ad4ab)
