### ISSUE TITLE
Provide a customizable snap handler

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#13]
Hi,

In some use cases, I need to return more than the data in store (some ref/metadata). I don't think it should be here by default so I though of passing a handler to the node, like in the `firestore` object.

This handler, if present, would be called [instead of `snapHandler`](https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L51). This way, anyone could get exactly what he wants for every query.

What do you think of that? Do you have an alternate idea?

**Comment by sichangi** [comment]
Hi, 
This was recently implemented [here](https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L68).
Though I think a better way to actually implement it is by having the option to have the ``snapHandler`` function handle it or simply return the ``referenceQuery`` as linked above.

Though adding more UI options, may make the node seem bloated with functionality, I may limit access to the option only through the ``msg`` object

**Comment by JbIPS** [comment]
I agree to not set that in the UI, since writing function in it is not very ideal.

I don't understand how the `referenceQuery` would achieve something like that. Could you provide an example please? 

And if you think a custom handler would be useful, I'll implement it soon.

**Comment by sichangi** [comment]
The ``referenceQuery`` exposes the [``DocumentReference``](https://firebase.google.com/docs/reference/node/firebase.firestore.DocumentReference.html) class which allows you to extend the query to your liking as well as adding your own handlers in subsequent nodes.

So in a subsequent function node, you can perform [asynchronous](https://nodered.org/docs/writing-functions#sending-messages-asynchronously) actions like so
```javascript
msg.firebase.referenceQuery.get().then(snap => {
   // Your custom snap handler right here
   node.send({your_data: snap.data()})
})
```

**Comment by sichangi** [comment]
Furthermore going with this approach opens up these additional [methods](https://firebase.google.com/docs/reference/node/firebase.firestore.DocumentReference.html#methods) for anyone who needs them.

**Comment by JbIPS** [comment]
I created a simple PR of the behavior I was expecting, feel free to change/refuse it if you want to stick with the `referenceQuery` approach (but maybe rename it to `documentReference` or something like that).

Hope this will help :smiley:

**Comment by JbIPS** [comment]
I must be doing something wrong but this is not working here.
I added a function node after my Firestore node with: 
```js
msg.firestore.query.get().then(snap => {
    let docArray = {}
    snap.forEach(function (snapDoc) {
        ...
    })                                                                                                                                
    node.send(docArray);
});
return;
```
First issue: `get is not a function`. So I logged `msg.firestore.query` and it's an array with my where clauses. 
It seamed fine in the debugger but messed up in the next node. I already know the VM of function nodes can mess up things, I don't know if this is related.

Do you have a working example please?

**Comment by sichangi** [comment]
base on [this](https://github.com/sichangi/node-red-contrib-cloud-firestore#extensibility--further-uses)
it should be
```javascript
msg.firebase.query.get()
```

I probably should change the firebase key to firestore to make it intuitive

**Comment by sichangi** [comment]
additionally include your earlier proposition of defining whether to use the default of extend with a custom one like you've done so that you don't fire the query twice

**Comment by JbIPS** [comment]
That's exactly what I did, but I cannot `get()` this query. Is there any conditions or requirements?
![screenshot](https://www.dropbox.com/s/8zfwyt3rvomgmt9/node-red_screenshot.png?dl=0)

**Comment by sichangi** [comment]
Change it from ``msg.firestore`` to ``msg.firebase``

**Comment by JbIPS** [comment]
Right, sorry, I didn't see that change! It works better like this but the naming can be confusing :sweat_smile: 

Thank you for your help

**Comment by sichangi** [comment]
No problem,😅 It happens

**Comment by sichangi** [comment]
@JbIPS , 
Kindly review this pull request => #20
