### ISSUE TITLE
Read in realtime mode stops listening

### ISSUE THREAD

**Issue by Mike120Git** [sichangi/node-red-contrib-cloud-firestore#16]
Hi!
I noticed that Read node in realtime mode stops listening for database changes after some time. 

Restarting node red does help. 

I need reliable 24/7 change listener. 
Is there a way to detect the problem and force the listener to reconnect to Firebase? 
Or make it reconect to Firebase periodically?

Could you please give me some advice how to diagnose and fix my problem?

Greetings, 
Mike

**Comment by sichangi** [comment]
Did you get this solved, or found a work around?

**Comment by Mike120Git** [comment]
The problem disappeared after hardware upgrade (to RPi 4) and full system / node-red reinstall. I am not sure what exactly caused the issue, I noticed also some network connectivity problems with the old setup. 
Now it is working 24/7 flawlessly. 
It looks like the problem was not related to the code, sorry to bother you.
