### ISSUE TITLE
Service Account Configuration for Heroku

### ISSUE THREAD

**Issue by Coedcoe** [sichangi/node-red-contrib-cloud-firestore#17]
I have Node-RED hosted on Heroku and when Heroku cycles on a daily basis the serviceAccountJson is getting removed. Is there anyway to configure this to be persistent in the Node Flow?

**Comment by sichangi** [comment]
Hi @Coedcoe, 
At the moment this is not possible, 
though after looking around a possible fix to this might be for the admin node to use the [Context API](https://nodered.org/docs/api/context/) to store and retrieve the serviceAccount contents on load.

**Comment by Coedcoe** [comment]
Do you know how I can get that context api to pass into the serviceAccountJson field? I tried environment variables and saving it directly in the flow Json with no luck.

**Comment by sichangi** [comment]
From your end as a consumer of the node, maybe not,
but if you're willing to make a PR for this, that'd be great 😄
