### ISSUE TITLE
Firestore  set({"data": data},{merge:true})

### ISSUE THREAD

**Issue by Noller-BASCO** [sichangi/node-red-contrib-cloud-firestore#2]
I am having issues getting the firestore set function to work with "merge:true" [link](https://firebase.google.com/docs/firestore/manage-data/add-data). 

Is there a way to pass to do this at the current time?

**Comment by sichangi** [comment]
At the moment that is not supported.
I'll have a look on how best I can add support for passing in options.

**Comment by sichangi** [comment]
I've added partial support for this, through dynamically passing in the options as documented under the [Firestore Write](https://github.com/sichangi/node-red-contrib-cloud-firestore#firestore-write) section.
Will be working on passing in options through the editor a bit later though.

I hope this helps.
