### ISSUE TITLE
Not able to choose the document name

### ISSUE THREAD

**Issue by jmsalomr** [sichangi/node-red-contrib-cloud-firestore#21]
Hi,

I'm trying to put a name for the document to add in the collection configured in the node adding a firestore property in the precedent function node:

msg.firestore = {
    'document': msg.payload.chatId,
    'operation': 'add'
}

and although the property gets into the Firestote in node, the name of the document still is putted automatically.
Am I doing something wrong?

**Comment by sichangi** [comment]
Hello,
If using the ``add`` operation, the firebase sdk will auto generate the document Id for you,
instead change the operation to ``set``.

**Comment by jmsalomr** [comment]
It works. Thank you very much!
