### ISSUE TITLE
Externalize Firebase admin

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#23]
Hi,

I've encountered an issue when trying to use another Firebase node (firebase-auth) because it also defined an admin node.

The idea (as discussed [here](https://discourse.nodered.org/t/managing-conflicts-in-firebase-nodes/16952/8)) would be to have a standalone admin node as a peer dependency in this project and the other. I tried it (https://github.com/JbIPS/node-red-contrib-cloud-firebase-admin), heavily inspired by your code, and it requires only minor change in your project (package.json and the way you get the firestore/firebase object).

Would this be an acceptable evolution for you?

**Comment by sichangi** [comment]
Hey,
This seems like a valid issue and will definitely be willing to take on the necessary changes.

**Comment by JbIPS** [comment]
Thanks! You can already review the project linked in previous comment (if you want) and I'll create a PR next week for the integration. 

Have a good day

**Comment by sichangi** [comment]
I'm gonna have to reopen this issue as npm does not automatically install peer dependencies & your module does not seem to show up in the pallet manager, neither does it appear in the library.
Seems I didn't catch these when I was testing it manually

Cloud firebase admin -> [here](https://flows.nodered.org/node/node-red-contrib-cloud-firebase-admin)
Reference to npm's announcement -> [here](https://blog.npmjs.org/post/110924823920/npm-weekly-5)

**Comment by JbIPS** [comment]
Sorry, I missed it too since I only install via the command line.

I updated the package  keywords so it should appears in the console.

But you're right, `peerDependencies` won't be installed automatically. Maybe I should add the instruction in the documentation and add a check ( require it, verify it exists) at runtime?

**Comment by JbIPS** [comment]
The repository is now [listed](https://flows.nodered.org/node/node-red-contrib-cloud-firebase-admin).
I made a few adjustment in the exported properties so it would be a drop-in replacement.

Let me know if you see any needed modifications.
