### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by srebling** [sichangi/node-red-contrib-cloud-firestore#24]
Can this be used with Firebase Authentication? (email/password)

**Comment by sichangi** [comment]
Hello, @srebling 
Please expound a bit on your use case / what you are trying to achieve?

**Comment by srebling** [comment]
Thanks for the reply.
Trying to read/write a database with security rules restricted to authenticated users. 
`service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}`
Only works if set open.
      allow read, write: if true;

**Comment by sichangi** [comment]
Well,
This module wraps the Admin SDK, and from looking through the [docs](https://firebase.google.com/docs/rules/manage-deploy#use_the_admin_sdk), It seems like the Admin SDK has a much higher access level and requires no authentication for it to work.
