### ISSUE TITLE
'Firestore In' only accepting string as Query input?

### ISSUE THREAD

**Issue by MichielVanthoor** [sichangi/node-red-contrib-cloud-firestore#25]
In the 'Query' section within the config of the 'Firestore In' node, I'm trying to compare fields with numbers and boolean values without success. I suspect the inputs within the config of the node are automatically handled as strings?

As as work-around I did try to create msg.firestore as an input, but it was overridden by the (mandatory) input values within the config of the node.

**Comment by sichangi** [comment]
Hey @MichielVanthoor, 
That's a pretty interesting discovery, and you're right it is an input field of type text,
Am not so sure on how best to handle other types, cause booleans' need a checkbox for that kind of check.
Alternatively, doing JS checks for booleans may be biased against cases where ``true / false`` is an actual string.

Do you have any suggestions?

**Comment by MichielVanthoor** [comment]
Hi @sichangi, thanks for coming back to me. Next to the booleans, I'm trying to compare dates as well, you think that is easier to implement?

As a work-around, I'm thinking of  writing my own JS node to further filter the data I get back from Firestore. Given I don't deal with a lot of data, this should do the trick for me as well.

**Comment by sichangi** [comment]
SGTM,
Although as you mentioned earlier, you could also just sanitize your data through a function node and pass them into the Firestore Node over the ``msg.firestore`` field. But this also depends on how you are using the Node.

I'll close this for now. Feel free to comment here after or open a new one if you have any other issues. Cheers 😄
