### ISSUE TITLE
Custom handler for realtime

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#27]
Hi,

I have a hard time combining realtime requests and custom handler.

For the handler, I use de `deactivate` option and add a `.onSnapshot()` in a function node later, but a listener is added at [startup](https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L23), multiplying the events.
But removing the `realtime` option force me to initiate the flow somehow.

One idea to conciliate all of this would be to return the [`QueryDocumentSnapshot`](https://firebase.google.com/docs/reference/js/firebase.firestore.QueryDocumentSnapshot) (not only the data), maybe in the `msg.firestore` object. Since I need to get the [`ref`](https://firebase.google.com/docs/reference/js/firebase.firestore.QueryDocumentSnapshot#ref), then the parent, it would be OK.

Do you have other ideas? Any thoughts ?

**Comment by sichangi** [comment]
Hello,

You can actually disable the default handler with the ``disableHandler`` option and simply return the built Query without it being called. you can find it [here](https://github.com/sichangi/node-red-contrib-cloud-firestore#firestore-read).

You can also get the firestore object on the ``msg.firebase`` object as mentioned [here](https://github.com/sichangi/node-red-contrib-cloud-firestore#extensibility--further-uses)

**Comment by sichangi** [comment]
Oh wait you are referring to passing in options to the init call made for real-time functionality.

😅 my bad.

**Comment by JbIPS** [comment]
> Hello,
> 
> You can actually disable the default handler with the `disableHandler` option and simply return the built Query without it being called. you can find it [here](https://github.com/sichangi/node-red-contrib-cloud-firestore#firestore-read).
> 
> You can also get the firestore object on the `msg.firebase` object as mentioned [here](https://github.com/sichangi/node-red-contrib-cloud-firestore#extensibility--further-uses)

Yes, I try this approach first but it's in conflict with the init.

Do you have any ideas? Personally, I'd recommend the possibility to overwrite `snapHandler` via the `msg.firestore` object

**Comment by sichangi** [comment]
Hmm... I agree with you on that idea, 
though the tricky question is how to parse & handle the ``snapHandler`` in a way that is intuitive to the user.

I've read through node-reds core function node and kinda have a good idea on how to handle it

[Here](https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/core/function/10-function.js#L247) is a reference if interested

**Comment by JbIPS** [comment]
To begin with, I'd let that option to "expert user", a.k.a. from the `firestore` object only (without UI).

If we see an adoption of this feature, we could think about a "expert" section in the UI.

Would you be OK with this?

**Comment by JbIPS** [comment]
2min in the code and I understand my mistake: we have to overwrite at init time, hence in the UI...

I'll look at the function node and try to copy it.

**Comment by sichangi** [comment]
Yeah,
We could also just have a checkbox that reveals the input UI to simplify it

**Comment by JbIPS** [comment]
Coincidentally, another node I'm working on is doing just that -> https://github.com/zuhito/node-red-contrib-sendgrid/commit/7dd1370e37475b8b951dd835a6c854eef9ba0955#diff-9e8967940921ae3e786b1d4350d0f8beR31

I'll try to make it simple

**Comment by sichangi** [comment]
This is now in the latest release & has been documented.
Thanks a ton for your input 👍
