### ISSUE TITLE
Error manipulating HTTP2 socket

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#29]
Hi,

When using realtime, I get an error on each `onSnapshot()` call: 
```
Error [ERR_HTTP2_NO_SOCKET_MANIPULATION]: HTTP/2 sockets should not be directly manipulated (e.g. read and written)
```
This come from NodeRED trying to manipulate the `firebase` object (which now contains a socket) when sending the message to the next node.

This `firebase` object is set [here](https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L28) but I don't know why. It's not mentioned in the documentation and I can't find any usage for it.

Is it legacy? Can we remove it?

**Comment by sichangi** [comment]
Hmm.. am unable to reproduce the error, could you export a sample flow with the issue?
Just make sure to leave out your service account details 😄

The firebase object is documented as a means to further extend the nodes, [here](https://github.com/sichangi/node-red-contrib-cloud-firestore#extensibility--further-uses) it is in the readme

**Comment by JbIPS** [comment]
Here's a basic one, strip to the minimum
```
[{"id":"430ed70f.da3238","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"44c66a54.9d6a3c","type":"Firestore in","z":"430ed70f.da3238","name":"","collection":"promotions","group":false,"document":"","realtime":true,"query":[],"admin":"76b39ac.14e5b64","snapHandler":"","x":150,"y":140,"wires":[["ab20e835.c79a58","695fb1ac.dec24"]]},{"id":"ab20e835.c79a58","type":"change","z":"430ed70f.da3238","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"firebase","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":340,"y":160,"wires":[["d3962993.d2c3"]]},{"id":"695fb1ac.dec24","type":"debug","z":"430ed70f.da3238","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":310,"y":60,"wires":[]},{"id":"d3962993.d2c3","type":"debug","z":"430ed70f.da3238","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":500,"y":140,"wires":[]},{"id":"76b39ac.14e5b64","type":"firebase admin","z":"","name":"Stan"}]
```
on deploy, I see the error in the console.

**Comment by sichangi** [comment]
So am guessing you're trying to remove the firebase object from the ``msg`` object.
Considering that there are some ``readonly`` properties in there, you might not be able to just replace them.
Although, now that we have a customizable snapshot handler, you can actually delete it like so
```js
delete msg.firebase

// the rest of your snap handler
```

**Comment by sichangi** [comment]
In my latest commit (not yet released), I've made the ``firebase`` object ejection optional, so I believe that might also solve this issue for you.
