### ISSUE TITLE
Not able to read a document

### ISSUE THREAD

**Issue by cevatkerim** [sichangi/node-red-contrib-cloud-firestore#30]
Getting this error when I try to read a document. Setting it has no issues:

"TypeError: Cannot set property bytesRead of #<Socket> which has only a getter"

**Comment by sichangi** [comment]
Hey @cevatkerim, 
Might need some more context, on this? 
How is the data structured...? Does this happen all the time?

**Comment by sichangi** [comment]
This might be related to an issues regarding the exported firebase object,
we've made the firebase object optional so am hoping this might fix the issue.

If not, feel free to comment / open a new issues
