### ISSUE TITLE
Error "No firebase admin specified"

### ISSUE THREAD

**Issue by thanksmister** [sichangi/node-red-contrib-cloud-firestore#31]
I setup the node and added the Firebase Admin  SDK JSON to the config node. When I deploy the project, I receive the following errors: 

> /12/2020, 9:00:44 PMnode: Admin JSON
> msg : error
> "Error: Firebase app named "iot-alarm-system" already exists. This means you called initializeApp() more than once with the same app name as the second argument. Make sure you provide a unique name every time you call initializeApp()."
> 4/12/2020, 9:00:44 PMnode: Firebae Admin
> msg : string[27]
> "No firebase admin specified"

I do have a firebase admin specified and I believe it's setup correctly.   Here is a snapshot of my admin settings (deprecated some information). 

<img width="300" alt="admin_json" src="https://user-images.githubusercontent.com/142340/79082983-86e7d100-7d01-11ea-831f-e6fe52917db3.png">

**Comment by thanksmister** [comment]
This seems to be an issue when you have other Google Core IoT nodes and Firebase nodes installed that have the same Admin SDK Json authentication method.  Closing for now.

**Comment by JbIPS** [comment]
Hi @thanksmister !
Yes, if you use another node wih a Firebase admin node, you'll have some conflicts. 

We're currently working on using a shared node between Firebase nodes. Which one are you using?

Thank you

**Comment by thanksmister** [comment]
I was using https://github.com/cyberflohr/node-red-contrib-google-iot-core/

**Comment by JbIPS** [comment]
Do you have any idea why this would call an initialization of Firebase? I looked a bit and it's not even dependent of `firebase-admin`

**Comment by thanksmister** [comment]
They both seem to use the new Admin SDK with JSON for authentication?
