### ISSUE TITLE
Use mustache template in the UI

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#32]
Most of the time, I have to add a node before the Firestore one just to create the `msg.firestore` object dynamically.

Wouldn't it be great to have MustacheJS templating in the editor for `collection` and `document`? It would be the same as the HTTP Request node.

**Comment by sichangi** [comment]
Sounds pretty cool,
Just so we are on the same page is this how it would look like?
```
msg.col = 'users'
msg.doc = 'someone'
```

then in the node, you have the collection value set as 
```
{{{ col }}}
```
and the document
```
{{{ doc }}}
```

**Comment by JbIPS** [comment]
Yes, but only 2 braces :smile: 
input:
```
msg = {
    payload: 'foo',
    promotion: {
      id: 'bar
    }'
};
```
and configuration of the node in the UI editor: 
![Screenshot from 2020-04-19 13-42-36](https://user-images.githubusercontent.com/2248473/79686860-ab810300-8243-11ea-8272-c89c66c47d68.png)

**Comment by sichangi** [comment]
😅 Noted.
So on implementation am guessing it's a matter of parsing the collection / document value for mustache's then replacing the corresponding message value with it.

Do you wanna take a shot at this or should I?
Cause It seems light enough to publish in the next release with our other patches

**Comment by JbIPS** [comment]
It's very lightweight, just rendering the collection and document with `Mustache.render(col, msg)`.

I already implemented it to try, works fine. Let me just rebase with your latest commits and I'll do a PR
