### ISSUE TITLE
Use eject mode for msg.firestore

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#38]
Hi,

Just saw your `eject` mechanism and it gave me an idea: why not eject the `firestore` object too?

In my flows, I do numerous consecutive read in Firestore. I always change the collection and the document (that's easy) but I frequently forget about removing the query, ending with incoherent results.

Wouldn't it be nice to "clean up" after a query?

**Comment by sichangi** [comment]
Hey,
So in a nutshell, delete the firestore property after the node is done with it?

**Comment by JbIPS** [comment]
Yes

**Comment by sichangi** [comment]
I don't know if it's just me but even without adding any logic to the module, the firestore object doesn't seem to appear in the ``msg`` object downstream

**Comment by JbIPS** [comment]
I don't know, is it me?

Here a basic flow to try, I can see the whole `firestore` object after the query:
```json
[{"id":"280269ca.9d40ee","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"d02a7049.861c48","type":"inject","z":"280269ca.9d40ee","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":180,"wires":[["4632e5ee.6a6aec"]]},{"id":"4632e5ee.6a6aec","type":"change","z":"280269ca.9d40ee","name":"","rules":[{"t":"set","p":"firestore","pt":"msg","to":"{\"query\": [{\"where\": [\"size\", \"==\", 5]}]} ","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":260,"y":180,"wires":[["849af4f.466f288"]]},{"id":"849af4f.466f288","type":"Firestore in","z":"280269ca.9d40ee","name":"","collection":"random","group":false,"document":"","realtime":false,"query":[],"admin":"76b39ac.14e5b64","snapHandler":"","eject":false,"x":420,"y":180,"wires":[["b6b7d7ce.b8d89"]]},{"id":"b6b7d7ce.b8d89","type":"debug","z":"280269ca.9d40ee","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"firestore","targetType":"msg","x":570,"y":180,"wires":[]},{"id":"76b39ac.14e5b64","type":"firebase admin","z":"","name":"Stan"}]
```

**Comment by sichangi** [comment]
Oh, now I see why I didn't notice it.
Thanks 👍

**Comment by JbIPS** [comment]
So, do we cleanup? Always? Only when `!eject`?

**Comment by sichangi** [comment]
I think when ``!eject`` is fine. It gives people the option to have it or not
