### ISSUE TITLE
Dynamic config are made static

### ISSUE THREAD

**Issue by JbIPS** [sichangi/node-red-contrib-cloud-firestore#41]
I didn't notice it at first but you introduce a strange line in the [`input mechanism`](https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Read/ReadNode.js#L54).

The issue is, when using a template config (says `collection: {{myCollection}}`) in the editor, this line will set `this.collection` to the first context it come across:
1st call :
```
msg = {myCollection: 'foo'}
```
Now `this.config === 'foo'` (instead of `{{myCollection}}`).
So this:
```
msg = {myCollection:'bar'}
```
will still query the `foo` collection.

**Comment by JbIPS** [comment]
BTW, I don't understand why you would want to set `this.` property dynamically on input if the user hasn't set them in the editor.

**Comment by JbIPS** [comment]
Worst than that, today I found that, combined with the `firestore` leaking, configurations made upstream are forced to following nodes since config is merge in firestore.

Could we just get rid of all the merging and try to be as stateless as possible on input?

**Comment by sichangi** [comment]
Fixed in the latest commit
