### ISSUE TITLE
Firebase Admin

### ISSUE THREAD

**Issue by SDanieldK** [sichangi/node-red-contrib-cloud-firestore#45]
Hi there

Im trying inject a Service Account Json into the admin config. I would like to move my flow to another pi without having to manually input the Service Account Json.

Is there way to inject it or is there a way to export the flow with the Service Account Json attached.

Thanks!

**Comment by JbIPS** [comment]
Hello @SDanieldK,

The service account JSON is store in the credential of NodeRED. I don't think there is a way to inject one.

The only solution to move it to another machine is to move the credential file `flow_creds.json` along and to keep the same secret (in the config file) between machine.

**Comment by SDanieldK** [comment]
Hi JbIPS

Thank you for the quick response I will try that. 

All the best!
