### ISSUE TITLE
no way to add/create a document with specified ID

### ISSUE THREAD

**Issue by BorisDaich** [sichangi/node-red-contrib-cloud-firestore#47]
at least I could not find a way 

IMHO 
it seems that 
at https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/master/src/Write/WriteNode.js 
line 72
```

 switch (op) {
    case 'add':
      referenceQuery = this.firestore.collection(col).add(payload);
```

the `collection(col).add(payload); ` always will create a document with firestore assigned ID

====

proposal:
if document is set on "add" use it as an ID of the document created

**Comment by sichangi** [comment]
Hi @BorisDaich 👋 

I think you want to use the ``set`` operation linked [here](https://firebase.google.com/docs/firestore/manage-data/add-data#set_a_document). 
You can also dynamically set the documents ID as documented [here](https://github.com/sichangi/node-red-contrib-cloud-firestore#firestore-write)

**Comment by BorisDaich** [comment]
Great! It worked. Thank you so much for the prompt response. I am sorry it took me so long to try it and get back with the the Thank you! that you deserve!
