### ISSUE TITLE
Error when updating array of objects

### ISSUE THREAD

**Issue by lely475** [sichangi/node-red-contrib-cloud-firestore#51]
Hi,

I want to update a document containing an array of objects, lets say:
`buttonStatus = [{buttonId: 1, status: true,}, {buttonId: 2, status: false,},{buttonId: 3, status: true}]`
and instead of updating a single array element I would like to always update the full array.

When I try this:
![Bildschirmfoto 2020-10-13 um 21 15 25](https://user-images.githubusercontent.com/62755943/95905491-3a0cb200-0d99-11eb-9b5d-764a96f6f349.png)
`[{"id":"126fcdbd.03de62","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"c961f517.1ffa48","type":"function","z":"126fcdbd.03de62","name":"set buttonStatus","func":"msg.payload = {\"buttonStatus\": [{buttonId: 1, status: true,}, {buttonId: 2, status: false,},{buttonId: 3, status: true}]};\nmsg.firestore = {\n        collection: \"mycollection\",\n        document: \"mydocument\",\n        operation: \"update\"\n      }\nreturn msg;","outputs":1,"noerr":0,"x":370,"y":260,"wires":[["17c655ed.96f2aa"]]},{"id":"17c655ed.96f2aa","type":"Firestore out","z":"126fcdbd.03de62","name":"","collection":"/mycollection","document":"","operation":"update","admin":"6f442d7.c6ddd54","eject":false,"x":580,"y":260,"wires":[[]]},{"id":"dc4891f2.df239","type":"inject","z":"126fcdbd.03de62","name":"Inject","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":260,"wires":[["c961f517.1ffa48"]]},{"id":"6f442d7.c6ddd54","type":"firebase admin","z":"","name":"Firestore"}]`

I receive the follwoing error message: 
**Error: Cannot encode value: [object Object],[object Object],[object Object]**

Am I doing something wrong or is there a workaround for this?
Thank you already!

**Comment by sichangi** [comment]
Hey @lely475, 
Thanks for reporting this.

It seems the error is being thrown within the [SDK over here](https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/serializer.ts#L211)

I'll look into what's causing the issue as I've been able to replicate the issue.

**Comment by lely475** [comment]
Thank you, I appreciate it!

**Comment by lely475** [comment]
Hi @sichangi,
are there any updates on this issue?

**Comment by pcastilloq** [comment]
Hi, I have a similar error. And looking the error message I noticed that it said **Error: Cannot encode value: [object Object],[object Object],[object Object]** and in the SDK `throw new Error(`Cannot encode value: ${val}`);` so val = [object Object],[object Object],[object Object], but val should be recognized as a Array but is not [https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/serializer.ts#L172](SDK).

**Comment by 666Jaime666** [comment]
Hi, 
If anyone is still stuck on this issue. A dirty quick fix is to convert the msg.payload to JSON and back using the parser blocks. The issue seems to be that the values are not recognised as arrays. After being converted to JSON and back they are correctly recognised. Its ugly but it works

**Comment by sichangi** [comment]
@lely475 
For your use case you'd want to use the ``arrayUnion`` sentinel to append array items
