### ISSUE TITLE
Error: 13 INTERNAL: Failed to start HTTP/2 stream

### ISSUE THREAD

**Issue by Stasfe** [sichangi/node-red-contrib-cloud-firestore#53]
Hey,
I'm testing around with your nodes and everything worked as expected so far. But somehow over the weekend I got this error with write node when I was trying to update a document: `Error: 13 INTERNAL: Failed to start HTTP/2 stream`. 
What is it about and how to avoid it in future? After some clicking in the firebase and made some reads it starts working again.

**Comment by JbIPS** [comment]
Hi @Stasfe,

Could you tell us more about your flow? What's going in? I've never seen this error so maybe you have some special parameter in your `msg`.

**Comment by Stasfe** [comment]
Hi,
absolutely nothing speacial. I take a double value from my plc and update the value in the cloud.
![image](https://user-images.githubusercontent.com/46917944/121136228-b3c84300-c835-11eb-9d0b-e24c60c11c5c.png)

today morning I had the same issue: `Error: 13 INTERNAL: Failed to start HTTP/2 stream`, after I hit this 8 and 0 couple times, it goes away. 
With deadband node I watch the value and block if difference <1 to not overload the stream to the cloud.

And this is my function: 
![image](https://user-images.githubusercontent.com/46917944/121136581-19b4ca80-c836-11eb-994c-0b755345528e.png)


config of the write node:
![image](https://user-images.githubusercontent.com/46917944/121136786-51237700-c836-11eb-81bc-49aecae2d1f4.png)


Maybe somehow the stream gets closed, because the value dont change over night?

**Comment by JbIPS** [comment]
You're right, nothing's wrong with your data.

After some searches, I found out it's related with a [Google problem](https://github.com/googleapis/nodejs-datastore/issues/723). The discussion suggests updating your google dependencies, but the issue seems so random it's difficult to say it will solve it definitely.

Sorry for this not-so-good-news answer :sweat_smile:

**Comment by Stasfe** [comment]
What is meant by "update you google dependencies"? Do I have any? I just use this write node. Do I have to update something inside firebase?

**Comment by Stasfe** [comment]
So error still here, but I figured out that it happens over night. The whole day long is nothing and in the next morning the error is there. And I found out how to quit this error without restarting nodered. I just need to open service account file (where my admin accout allready exists) and just hit the update button without any changes, after that I need to deploy again and it starts working. 
can we somehow catch the error and maybe automate the update process?

**Comment by JbIPS** [comment]
If it happens over night, did you notice any network issue at this time?

Catching the error good be a good start but do you know where it come from? If "updating" the settings fixes it, maybe it's in the [initialization](https://github.com/sichangi/node-red-contrib-cloud-firestore/blob/c09059fab735f2b522174e487d000a47f0c7a972/src/admin/firebaseAdminNode.js#L8).

**Comment by Stasfe** [comment]
No I didnt notice any network issues, cause I also run a graph on the dashboard with data over http request and there are no gaps.
Also I just unpluged raspberry (where I run my node red) and plugged in again. The node works since nodered starts without issues.

I will try to write into another database on another raspy and see how it goes.

**Comment by Stasfe** [comment]
Hey, short update. 
I just clean up my code recently and use write node inside subflow with 2 instances. And it works fine now, I dont have any issues since 2 weeks now. 
I also had before 2 real time reading nodes. I will see how it goes when I implement them again.

**Comment by JbIPS** [comment]
Thank your for the update! I'm closing this one but feel free to reopen if you encounter issues again.

**Comment by Talakafafi** [comment]
How do you fill these fields like admin name and  Service Account Json  ?
