### ISSUE TITLE
send timestamp to firebase

### ISSUE THREAD

**Issue by filipedias1994** [sichangi/node-red-contrib-cloud-firestore#54]
Hi!
I'm trying to update fields of a document through a json via node-red. This field in Firebase is timestamp format, but when sending a json:

>  {"date":1623966732}

, the field in Firebase becomes number with the value sent.

Is there a way to send a timestamp and Firebase recognize it as a timestamp?

Thanks!

**Comment by JbIPS** [comment]
Hi,

Can you give us a sample of the JSON data?

When I need a `Timestamp` I send a Javascript `Date` to the Firebase node and it is interpreted as a timestamp in Firebase.
