### ISSUE TITLE
Error on Raspberry Pi Zero W: Liftoff bailout should not happen. Cause: Armv6 not supported

### ISSUE THREAD

**Issue by GaneshBaronAloir** [sichangi/node-red-contrib-cloud-firestore#55]
Hello, since I installed the library on my Raspberry Pi Zero W, node-red won't open and says the following error: Liftoff bailout should not happen. Cause: Armv6 not supported. Any fix or works around available?

**Comment by JbIPS** [comment]
Hi @GaneshBaronAloir,

It seems like NodeRed (or one of its dependencies) is not compatible with the architecture of your RPi Zero W (ARMv6).

I'm sorry but there is nothing we can do at our level.

**Comment by GaneshBaronAloir** [comment]
Hey @JbIPS just letting you know that I could track further down the problem coming from Firebase Auth.  Please note that Node-Red is fully compatible with RPi Zero W. I can use my project without any problem both Firebase Auth and Firebase can be installed on Node-Red on the Pi Zero. If I drag a Firestore node and commit it's fine, but as soon as I enter a Service Account JSON credentials it crashes and raise the error. The service credentials content is confirmed to be correct since I'm using it on a Rpi 4.

**Comment by JbIPS** [comment]
Thank you for the information, I wonder why the Service Account would provoke such a thing.
