### ISSUE TITLE
how loggin into FireStore

### ISSUE THREAD

**Issue by gzngzn** [sichangi/node-red-contrib-cloud-firestore#7]
Hi!
I cant login into firestore with  Service Account Json, pls say where i can copy data and how i can do paste. I tried alot ways from SDK Json and other, no way. Please help me! :)

**Comment by sichangi** [comment]
As described on the README file, admin configuration can be done through either read & write node from the first field in the form after which you can add a configuration.

>  "...taking in a name and the json contents of your apps service account credentials..."
