### ISSUE TITLE
Configure Node settings from node input

### ISSUE THREAD

**Issue by bigdoods** [sichangi/node-red-contrib-cloud-firestore#8]
Hi,

I have a usercase to configure my node-red instance via a config file. I would like to set the firestore client settings from msg.payload node input. For example:

_Function node passing message to Firestore in node_
```
msg.firestore = {
  "admin": {
    "type": "service_account",
    "project_id": "test-102",
    "private_key_id": "c96de...",
    "private_key": "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n",
    "client_email": "firebase-admin@test.iam.gserviceaccount.com",
    "client_id": "10597",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/..."
  },
 "name": "string",
 "collection": "string", 
 "document": "string",
 "realtime": true
}

 ```
Would this be difficult to do?

Thanks in advance.

**Comment by bigdoods** [comment]
I have been testing the Firestore read node and see in the documentation that there is support to configure the node collection, document and query when using the msg.firestore property. However, this is not working for me

**Comment by sichangi** [comment]
Hi @bigdoods, this seems to be a really interesting use case, I think this may take quite some effort to implement, though am open to any ideas you've got on how to do it.

In the mean time, I have tried to make the firestore nodes extensible as described [here](https://github.com/sichangi/node-red-contrib-cloud-firestore#extensibility--further-uses).

Hope it helps
